<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body bg-dark  rounded">

        <div class="d-flex justify-content-center">
          <img src="/img/logo-nsg.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2 class="text-center text-white p-3">Registro de novo usuário</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post" id="form_inscreverse">              

            <div class="form-group">
                <input type="text" name="nome" value="" id="nome_inscreverse" class="form-control" placeholder="Nome">                 
              </div>

            <div class="form-group">
                <input type="text" name="email" value="" id="email_inscreverse"class="form-control" placeholder="E-mail">                 
              </div>
           
              <div class="input-group">
                <input type="password" name="senha" id="senha_inscreverse" class="form-control " placeholder="Senha">
                <div class="input-group-append">
                <button class="btn btn-secondary fa-regular fa-eye disabled" type="button" id="btn_olho" onmouseenter="passwordTextEnter('senha_inscreverse')" onmouseout="passwordTextOut('senha_inscreverse')"  data-toggle="tooltip" data-placement="top" title="Exibir a senha"></button>                
                </div>     
              </div>

              <div class="row">               
               <div class="form-text col-md-6">
                <small class="invisible" id="small_inscreverse">Preencha as informaçoes para se cadastrar.</small>
                  <?php               
                    if(isset($_GET['usuarioExiste']) == 'sim') {?>
                      <small class="text-form text-danger">Email em uso.</small>
                    <?php }?>                
                    <?php               
                    if(isset($_GET['faltaInfo']) == 'sim') {?>
                      <small class="text-form text-danger">Preencha as informaçoes para se cadastrar.</small>
                    <?php }?>  
                    </div>
                  <div class="form-text col-md-6">
                    <div class="d-flex justify-content-end mr-3">
                      <a class="link" href="/">Login</a>
                  </div>
                  </div>                                   
              </div>

              </form>  
              <button type="submit" class="mt-3 btn btn-primary btn-block" id="btn_inscreverse" onclick="validarInscreverse()">Logar</button>             
            

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<?php

?>
