<?php 
    use MF\Model\Container; 
    $instaciaUser = Container::getModel('Usuario', 'users');                     
    $instaciaUser->__set('id', $_SESSION['id']);
    $usuario = $instaciaUser->recuperarUsuario();
    $tipoUser = $usuario['0']['tipo'];    
    
?>
<?php require('modal.phtml');?>
<div class="row bg-primary p-1 row_cabeçalho">  <!-- abertura row -->    

    <div class="col-md-1 d-flex justify-content-center ">
      <div class="d-flex justify-content-center">
          <span data-toggle="modal" data-target="#novoFuncionario">
            <i class="fa-solid fa-user-plus ico_add_func" data-toggle="tooltip" data-placement="top" title="Novo funcionário"></i>
          </span>
      </div>  
    </div>   

    <div class="col-md-1 d-flex justify-content-center ">
      <div class="d-flex justify-content-center">  
        <?php 
          if($tipoUser == 'User') {          
        ?>
        <span>
          <i class="fa-solid fa-user-xmark ico_delete_func_inativo" data-toggle="tooltip" data-placement="top" title="Essa ação está restrita apenas aos Adm's."></i>
      </span>
      <?php } 
        else if($tipoUser == 'Adm') {
      ?>
      <span data-toggle="modal" data-target="#desligarFuncionario">
          <i class="fa-solid fa-user-xmark ico_delete_func" data-toggle="tooltip" data-placement="top" title="Desligar funcionário"></i>
      <?php } ?>
      </div>

    </div>  

        <div class="col-md-6 d-flex justify-content-center">
            <span class="caixa-mat-funcionarios"style="font-size:22px; font-style:italic;">
                <b>Funcionários</b>
            </span>            
        </div>   

        <div class="col-md-4 d-flex  justify-content-center">    
          <div class="d-flex justify-content-center">
            <form action="pesquisarFuncionario " method="post">
                <div class="input-group"> 
                    <input type="text" name="pesquisa" id="pesquisa" class="form-control form-control-sm inputs caixa_pesquisa" placeholder="Pesquisar funcionário">
                    <div class="input-group-append">
                      <button class="btn btn-secondary btn-input btn_pesquisa caixa_pesquisa" type="submit" id="button-addon2" data-toggle="tooltip" data-placement="top" title="Pesquisar">
                        <i class="fa-solid fa-magnifying-glass ico_pesquisa"></i>
                      </button>
                      
                    </div>
                </div>
            </form>          
          </div>
        </div>                                

    </div>              <!-- fechamento row -->    
    
    <div class="row bg-white "> <!-- abertura row-->
        <div class="col-6 borda text-info cabeçalho">
            Nome 
        </div>
        <div class="col-2 borda text-info cabeçalho">
            Ferramentas
        </div>
        <div class="col-2 borda text-info cabeçalho">
            Histórico
        </div>
        <div class="col-2 borda text-info cabeçalho">
            Informações
        </div>
    </div>  <!-- fechamento row -->    
<script>
  var painel_2 = window.location        
</script>
<div class="row auxiliar_scroll_painel_funcionarios" id="scroll_painel_funcionarios" onresize="auxiliarScrollFuncionarios(painel_2)">
  <div class="col-12">
    <?php       
      $funcionarios = $this->view->Funcionarios;            
      foreach($funcionarios as $funcionario) {
        $nomeFuncionario = explode(' ', $funcionario['nome']);        
?>
       
    <div class="row bg-white" id="auxiliar_scroll_painel_funcionarios"> <!-- abertura row-->
    <span class="d-none" id="qtd_painel_funcionarios">
        <?=count($funcionarios)?>
    </span>   
        <div class="col-6 p-1 borda">
                <span class="nome_func"><?= $funcionario['nome'];?></span>
            </div>
            <div class="col-2 p-1 borda">
              <div class="d-flex justify-content-center">
                <span data-toggle="collapse" data-target="#collapseFerramentas<?=$funcionario['id']?>" aria-expanded="false" aria-controls="collapseExample1" onclick="colapse_ferramentas('<?=$funcionario['id']?>')">
                
                    <i class="fa-solid fa-screwdriver-wrench ico_ferramentas_func" id="ico_ferramentas<?=$funcionario['id']?>" data-toggle="tooltip" data-placement="left" title="Ferramentas do funcionário <?=$nomeFuncionario['0'] ?>"> </i>

                </span>
              </div>                 
            </div>                                  
            <div class="col-2 p-1 borda">
              <div class="d-flex justify-content-center">
                <span data-toggle="collapse" data-target="#collapseHistorico<?=$funcionario['id']?>" aria-expanded="false" aria-controls="collapseExample2" onclick="colapse_historico('<?=$funcionario['id']?>')">
                        <i class="fa-solid fa-clock-rotate-left ico_ferramentas_func" id="ico_historico<?=$funcionario['id']?>" data-toggle="tooltip" data-placement="left" title="Histórico de entrada/saída feitas pelo <?=$nomeFuncionario['0'] ?>."> </i>
                </span>
              </div>
            </div>
            <div class="col-2 p-1 borda">
              <div class="d-flex justify-content-center">
                <span data-toggle="collapse" data-target="#collapseInfo<?=$funcionario['id']?>" aria-expanded="false" aria-controls="collapseExample3" onclick="colapse_info('<?=$funcionario['id']?>')">    
                  <i class="fa-solid fa-address-card ico_ferramentas_func" id="ico_info<?=$funcionario['id']?>" data-toggle="tooltip" data-placement="left" title="Informações do funcionário <?=$nomeFuncionario['0']?>"></i>
                </span>
              </div>
          </div>


          <!-- collapse ferramentas -->
          <div class="auxiliar_ferramentas">

          <div class="row bg-secondary div_ferramentas collapse" id="collapseFerramentas<?=$funcionario['id']?>">                      
              <div class="col-12" id="col_12_fer">         
                <?php 
                 $conexao = $this->view->conexaoFunc;
                 $conexao->__set('nome', $funcionario['nome']);
                 $ferramentas = $conexao->ferramentasFuncionario();
                 if(count($ferramentas) == '0') {?>
                    <span class="pr-4 pl-4 text-white bold">Esse funcionário não possui ferramentas</span>
                 <?php } 
                 else { ?>                                       
                      <!-- tabela -->
                            <table class="table table-dark table-striped table-bordered">
                                <thead>
                                  <tr>
                                      <th scope="col">ID</th>
                                      <th scope="col">Ferramenta</th>
                                      <th scope="col">Quantidade</th>                                      
                                  </tr>
                                </thead>

                                <tbody>
                        <?php  
                        foreach($ferramentas as $ferramenta) {   
                        ?>
                          <tr>
                            <th class="th_ferramentas" scope="row"><?=$ferramenta['id']?></th>
                            <td class="td_ferramentas_descriçao"><?=$ferramenta['descriçao']?></td>
                            <td class="td_ferramentas_qtd"><?=$ferramenta['quantidade']?></td>
                          </tr>
                        <?php } ?> <!--fechamento foreach -->
                                </tbody>
                              </table>
                          <?php } ?> <!--fechamento else -->
                      <!-- tabela -->                                       
                  </div>              
          </div>    

          </div>
          <!-- collapse historico -->
          <div class="auxiliar_historico">

              <div class="row bg-light div_ferramentas collapse" id="collapseHistorico<?=$funcionario['id']?>">                      
                  <div class="col-12" id="col_12_hist">
                      <div class="justify-content-center">
                    <?php 
                      $conexao = $this->view->conexaoFunc;
                      $conexao->__set('nome', $funcionario['nome']);
                      $historico = $conexao->historicoFuncionario($_SESSION['dataDe'], $_SESSION['dataAte']);
                      if(count($historico) == 0) { ?>
                        <span class="pr-4 pl-4 text-dark bold"><b>Esse funcionário não possui registros</b></span>
                      <?php }
                      else {
                    ?>
                            <!-- tabela -->
                           <table class="table table-striped table-bordered">
                                <thead class="thead-dark">
                                  <tr>
                                      <th scope="col">Data</th>
                                      <th scope="col">Descrição</th>
                                      <th scope="col">QTD</th>
                                      <th scope="col">S/D</th>
                                      <th scope="col">Tipo</th>
                                  </tr>
                                </thead>
                        
                                <tbody>
                  <?php 
                    foreach ($historico as $hist) {
                  ?>
                                 <tr>
                                      <span data-toggle="tooltip" data-placement="left" title="<?=$hist['hora']?>"> 
                                      <th class="th_historico" scope="row"><?=$hist['data']?></th> 
                                      </span>
                                      <td class="td_historico_descriçao"><?=$hist['descriçao']?></td>            

                                      <?php 
                                          if ($hist['sd'] == 'S') {?>
                                            <td class="td_historico_qtd"> -<?=$hist['qtd'];?> </td>
                                          <?php }
                                          else { ?>
                                             <td class="td_historico_qtd"><?=$hist['qtd'];?> </td>
                                          <?php } ?>

                                      <td class="td_historico_sd"><?=$hist['sd']?></td>  
                                      <?php
                        if ($hist['tipo'] == 'M') {?>
                          <td class="td_historico_tipo"><i class="fa-solid fa-cart-flatbed ico_func"></i></td>
                        <?php }?>          
                        <?php
                        if ($hist['tipo'] == 'F') {?>
                          <td class="td_historico_tipo"><i class="fa-solid fa-screwdriver-wrench ico_func"></i></td>
                        <?php }?>                                                                                                                                          
                                </tr>   
                        <?php } ?>                             
                                </tbody>
                              </table>
                      <!-- tabela -->    
                      <?php } ?>
                      </div>
                  </div>
              </div>

          </div>
          <!-- collapse info -->
          <div class="auxiliar_info" id="auxiliar_info<?=$funcionario['id']?>" >

          <div class="row bg-info div_ferramentas collapse" id="collapseInfo<?=$funcionario['id']?>" onresize="auxiliarScrollFuncionarios(<?= $funcionario['id']?>)">                      
              <div class="col-1" id="col_12_info">
                  <div class="p-1 h-100 caixa_ico_info d-flex align-items-center">
                    <div class="caixa_ico_info_aux">
                        <i class="fa-solid fa-circle-user ico_user" onmouseenter="mudarIco()" onmouseout="esconderIco()" data-toggle="tooltip" data-placement="bottom" title="Alterar foto de funcionario"></i>
                        <i class="fa-solid fa-camera ico_camera text-light auxiliarIco invisible" onmouseenter="mudarIco()" onmouseout="esconderIco()"></i>
                    </div>                                       
                   
                  </div>                          
              </div>
              <div class="col pt-1 pb-3 pt-3 d-flex justify-content-center ">                                    
                  <table class="table table-dark table-bordered table-perso ">
                      <tbody>
                        <tr>
                          <th class="th_perso"scope="row">
                            Nome:                              
                          </th>
                          <td>
                          <?=$funcionario['nome']?>
                          </td>
                        </tr>

                        <tr>
                          <th class="th_perso" scope="row">
                              Função:
                          </th>
                          <td>
                          <?=$funcionario['funçao']?>
                          </td>
                        </tr>
                        
                        <tr>
                          <th class="th_perso" scope="row">
                              Contrato:
                          </th>
                          <td>
                          <?=$funcionario['contrato']?>
                          </td>
                        </tr>

                        <tr>
                          <th class="th_perso" scope="row">
                              CTPS:
                          </th>
                          <td >
                          <?=$funcionario['ctps']?>
                          </td>
                        </tr>

                        <tr>
                          <th class="th_perso" scope="row">
                              Telefone:
                          </th>
                          <td>
                          <?=$funcionario['telefone']?>
                          </td>
                        </tr>
                      </tbody>
                  </table>
                  <div class="float-left caixa_ico_edit">
                      <span data-toggle="modal" data-target="#editarFuncionario<?=$funcionario['id']?>">
                        <i class="fas fa-user-edit ico_edit_user pb-2" data-toggle="tooltip" data-placement="bottom" title="Editar informações"></i>
                      </span>  
                    </div>
              </div>
          </div> 

            <!-- MODAL EDITAR FUNCIONARIO -->
            <div class="modal fade" id="editarFuncionario<?=$funcionario['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title text-primary" id="exampleModalLabel">
                      Editar as informações do "<span class="text-dark"><?= $funcionario['nome']?></span>"
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form method="post" action="editarFuncionario?id=<?=$funcionario['id']?>" id="form_edit<?= $funcionario['id']?>">
                  <div class="modal-body">                 
                        <div class="form-group row">
                            <label for="nomeEdit<?= $funcionario['id']?>" class="col-sm-2 col-form-label" id="labe_edit_nome<?= $funcionario['id']?>">Nome:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nomeEdit<?= $funcionario['id']?>" name="nome" value="<?=$funcionario['nome']?>">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Funçao2<?= $funcionario['id']?>" class="col-sm-2 col-form-label" id="label_funcao<?= $funcionario['id']?>">Funçao:</label>
                            <div class="col-sm-10">                            
                                <select class="custom-select my-1 mr-sm-2" id="Funçao2<?= $funcionario['id']?>" name="funçao">
                                  <?php 
                                    if($funcionario['funçao'] == 'Auxiliar de eletricista') { ?>
                                      <option selected value="Auxiliar de eletricista">Auxiliar de eletricista</option>
                                  <?php }
                                    else {?>
                                    <option value="Auxiliar de eletricista">Auxiliar de eletricista</option
                                    >                                 
                                   <?php }?>
                              
                                   <?php 
                                    if($funcionario['funçao'] == 'Auxiliar de manutençao') { ?>
                                      <option selected value="Auxiliar de manutençao">Auxiliar de manutenção</option>  
                                  <?php }
                                    else {?>
                                    <option value="Auxiliar de manutençao">Auxiliar de manutenção</option>  
                                   <?php }?>

                                   <?php 
                                    if($funcionario['funçao'] == 'Auxiliar de refrigeraçao') { ?>
                                       <option selected value="Auxiliar de refrigeraçao">Auxiliar de refrigeração</option>
                                  <?php }
                                    else {?>
                                     <option value="Auxiliar de refrigeraçao">Auxiliar de refrigeração</option>
                                   <?php }?>  
                                   <?php 
                                    if($funcionario['funçao'] == 'Eletricista') { ?>
                                       <option selected value="Eletricista">Eletricista</option>
                                  <?php }
                                    else {?>
                                      <option value="Eletricista">Eletricista</option> 
                                   <?php }?> 

                                   <?php 
                                    if($funcionario['funçao'] == 'Mecânico de Refrigeração') { ?>
                                       <option selected value="Mecânico de Refrigeração">Mecânico de Refrigeração</option>
                                  <?php }
                                    else {?>
                                      <option value="Mecânico de Refrigeração">Mecânico de Refrigeração</option> 
                                   <?php }?>
                                  
                                   
                                   <?php 
                                    if($funcionario['funçao'] == 'Técnico em Refrigeração') { ?>                                       
                                       <option selected value="Técnico em Refrigeração">Técnico em Refrigeração</option>          
                                  <?php }
                                    else {?>
                                      <option value="Técnico em Refrigeração">Técnico em Refrigeração</option>          
                                   <?php }?>

                                   <option value="Técnico em Refrigeração">Técnico em Refrigeração</option>          
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                          <label for="Contrato2<?= $funcionario['id']?>" class="col-sm-2 col-form-label">Contrato:</label>
                          <div class="col-sm-10">
                              <select class="custom-select my-1 mr-sm-2" id="Contrato2<?= $funcionario['id']?>" name="contrato">
                                  <?php 
                                    if($funcionario['contrato'] == 'MANUTENÇAO - RO') { ?>
                                       <option selected value="MANUTENÇAO - RO">MANUTENÇÃO - RO </option>                
                                  <?php }
                                    else {?>
                                       <option value="MANUTENÇAO - RO">MANUTENÇÃO - RO </option>         
                                   <?php }?>  
                                   
                                   <?php 
                                    if($funcionario['contrato'] == 'FACILITIES - RO') { ?>
                                      <option selected value="FACILITIES - RO">FACILITIES - RO </option>
                                  <?php }
                                    else {?>
                                      <option value="FACILITIES - RO">FACILITIES - RO </option>
                                   <?php }?>                                                                                                                                                    
                              </select>
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="CPTS2<?= $funcionario['id']?>" class="col-sm-2 col-form-label">CPTS:</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" id="CPTS2<?= $funcionario['id']?>" name="ctps" value="<?=$funcionario['ctps']?>" placeholder="Carteira de trabalho do funcionário.">
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="tel2<?= $funcionario['id']?>" class="col-sm-2 col-form-label">Telefone:</label>
                          <div class="col-sm-10">
                            <input type="tel" class="form-control" id="tel2<?= $funcionario['id']?>" name="telefone" placeholder="(**) *****-****" value="<?=$funcionario['telefone']?>">
                          </div>
                      </div>                                    
                      <small class="invisible" id="retorno_edit<?= $funcionario['id']?>">O funcionário precisa de um nome!</small>
                  </div>                  
                  </form>
                  <div class="modal-footer" id="caixa_btn_edit<?= $funcionario['id']?>">                    
                    <button type="subtmit" class="btn btn-success" onclick="validarEdit('<?= $funcionario['id']?>')">Salvar mudanças</button>
                  </div>                  
                </div>
              </div>
            </div>
          </div>          
    </div>      <!-- fechamento row -->     
<?php } ?>
  </div>
</div>
                          <!-- RETORNO VISUAL PARA O USUARIO -->

<?php 
    if(isset($_GET['novoFunc']) == 'sucesso') {?>                          
      <div class="alert alert-success alert-dismissible alert_bottom fade show fixed-bottom" role="alert">
             Funcionario adicionado com sucesso!
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
      </div>
<?php } ?>

<?php 
    if(isset($_GET['desligaFunc']) == 'sucesso') {?>                          
      <div class="alert alert-success alert-dismissible alert_bottom fade show fixed-bottom" role="alert">
             Funcionario desligado com sucesso!
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
      </div>
<?php } ?>

<?php 
    if(isset($_GET['atualizaçao']) == 'sucesso') {?>                          
      <div class="alert alert-success alert-dismissible alert_bottom fade show fixed-bottom" role="alert">
             Ficha de funcionario atualizada com sucesso!
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
      </div>
<?php } ?>

</div>      <!-- fechamento container layout_2 -->  

<div class="float-right fixed-bottom d-flex justify-conten-center nav_painel" >
      <ul class="nav ul_painel d-flex justify-content-center ">
      <li class="nav-item">
        <div class="d-flex justify-content-center">
          <a class="nav-link btn btn-block btn-outline-primary fa-solid fa-cart-flatbed btn_nav" id="ico_ferramentas" data-toggle="tooltip" data-placement="top" title="Estoque de material" onclick="painel_materiais()"></a>
        </div>
      </li>
      <li class="nav-item">
        <div class="d-flex justify-content-center">
          <a class="nav-link btn btn-block btn-outline-primary  fa-solid fa-screwdriver-wrench btn_nav" id="ico_ferramentas"data-toggle="tooltip" data-placement="top" title="Estoque de ferramentas" onclick="painel_ferramentas()"></a>
        </div>        
      </li>
      <li class="nav-item">
        <div class="d-flex justify-content-center">
          <a class="nav-link btn btn-block btn-outline-primary active fa-solid fa-helmet-safety btn_nav" data-toggle="tooltip" data-placement="top" title="Funcionários"></a>
        </div>           
      </li>
      <li class="nav-item">
        <div class="d-flex justify-content-center">
          <a class="nav-link btn btn-block btn-outline-primary fa-solid fa-clock-rotate-left btn_nav" data-toggle="tooltip" data-placement="bottom" title="Histórico" onclick="painel_historico()"></a>          
        </div>            
      </li>
    </ul>
  </div>


  </body>
</html>

