<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Almoxarifado NSG</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">    
    <!-- <link rel="stylesheet" href="style.css"> -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/1841e9c55b.js" crossorigin="anonymous"></script>
    <script src="script.js"></script>
    <link rel="icon" href="img/favico.png" sizes="192x192"/>

    <style>
        html, body {
        height: 100%;          
        }
        .cx_login {
            position: relative;
            bottom: 50px;
        }
        #titulo_index {     
            font-style: italic;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }
        #btn_olho:hover {
        cursor: auto;     
        }
        #btn_olho {
            font-size: 15px;
            width: 50px;
        }
        .table td, .table th {
            padding:1rem;
        }
        #table_seleciona_filial {
            border-rad
        }
        .th_seleciona_filal {
            width: 15%;
        }
        .text_seleciona_contrato {
            font-weight: bold;
            position: relative;
            top: 6px;
        }
        #ico_saida {
        font-size: 25px;
        transition-property: color;
        transition-duration: 0.25s
        }
        #ico_saida:hover {
            color: white;     
        }
        #icone_user {     
            margin-top: 7px;
            margin-bottom: 5px;
            font-size: 20px;
        }
        .text-painel {
        font-size: 14px;
        font-style: italic;    
        }
        .card-body {
            padding-left: 0.9rem;
            padding-right: 0.9rem;
        }
    </style>

</head>
<body class="bg-dark">       
   
    <?=$this->content();?>        
</body>
</html>